"""Add ON DELETE CASCADE to progress.book_id

Revision ID: 1503c51aa4c7
Revises: 3c9d90f5ec1a
Create Date: 2025-07-01 12:09:22.701950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1503c51aa4c7'
down_revision: Union[str, None] = '3c9d90f5ec1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
