"""changed collumns for progress table again

Revision ID: 3c9d90f5ec1a
Revises: ca59181708f0
Create Date: 2025-06-16 20:43:47.370898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c9d90f5ec1a'
down_revision: Union[str, None] = 'ca59181708f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progress', sa.Column('percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('progress', 'percentage')
    # ### end Alembic commands ###
