"""changed collumns

Revision ID: 41044cb61e0a
Revises: 52aa8c0440ac
Create Date: 2025-05-05 16:15:42.476406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41044cb61e0a'
down_revision: Union[str, None] = '52aa8c0440ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('profile_picture', sa.LargeBinary(), nullable=True))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('user', 'profile_picture')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
