"""changed collumns for progress table

Revision ID: ca59181708f0
Revises: 34e0a4e228af
Create Date: 2025-06-14 14:35:59.130667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca59181708f0'
down_revision: Union[str, None] = '34e0a4e228af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('progress', 'percentage')
    op.drop_column('progress', 'character_position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progress', sa.Column('character_position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('progress', sa.Column('percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
