"""book_url changed to nullable

Revision ID: ee0846f8e797
Revises: e72332119d34
Create Date: 2025-06-08 19:36:55.033907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee0846f8e797'
down_revision: Union[str, None] = 'e72332119d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'book_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'book_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
